spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.253.128:3306/user_center?useSSL=false #使用虚拟机模拟远程服务器（没钱）
    username: root
    password: root
  redis:
    host: 192.168.253.128
    port: 6379
    password: 123
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s

